### ISSUE TITLE
Ability to style legend text color

### ISSUE THREAD

**Issue by susmita-vps** [esnet/react-timeseries-charts#112]
I need to render the graph legend against a black background 
I had to render a MultiSeries Graph, which worked fine till I found this small bug in which the color of the legend text is hardcoded in styler.js - line #174 :

line #174 in style.js - https://github.com/esnet//blame/master/src/js/styler.js

var labelStyle = {
        fontSize: 'normal',
        color: '#333',
        paddingRight: 10,
        cursor: 'pointer'
      };

The  #333 is not very visible on black background and this is a show stopper for me.

**Comment by pjm17971** [comment]
Thanks for this report.

Yes, the Styler is supposed to map a type of data (say "speed") to a style ("red"). At this point it isn't a general way of theming the structural elements of the chart such as line and label colors. Eventually you'll be able to do that but not today.

There's a couple of ways around this:
 - You can pass an object in as the style, rather than a styler. The default object can be seen here: https://github.com/esnet/react-timeseries-charts/blob/master/src/components/Legend.js#L18
 - You may also be able to subclass the Styler object itself and reimplement the legend handler to put in the new colors. Really the styler object is there to take a small handful of parameters and build up the object used in option 1.

Neither option is ideal, unfortunately, but it might get you unstuck.

-Peter

**Comment by JulesAU** [comment]
@pjm17971  Is this workaround also applicable to `EventMarker`? I've been having styling issues with those also.
