### ISSUE TITLE
Problem displaying a bar per hour with the BarChart

### ISSUE THREAD

**Issue by loganbfisher** [esnet/react-timeseries-charts#122]
My Current Problem:
I am trying to display a bar every hour.  But I keep getting this image below.  Looks like they are stacking instead of lining up side by side.

![](https://content.screencast.com/users/loganfisher/folders/Jing/media/88bc8350-d7cc-41f8-a0e1-f3e236f7a3ab/00000176.png)

```
// Time Range
const timeRange = new TimeRange(['2017-01-30', '2017-01-31']);

// Graph Data 
const inventoryData = [
 ["2017-01-30T11:58:38.741Z", 34],
 ["2017-01-30T12:58:01.940Z", 54],
 ["2017-01-30T13:57:37.945Z", 67]
]

// Time Series
const inventoryTimeSeries = new TimeSeries({
    name: "inventory",
    columns: ["index","value"],
    points: inventoryData
});

// BarChart
<BarChart
   axis="inventory"
   columns={["value"]}
   style={inventoryStyles}
   series={inventoryTimeSeries}/>
```

**Comment by pjm17971** [comment]
BarCharts are supposed to be for aggregated values (e.g. average of many points over an hour), so the hours themselves are specified with an Index. An Index is a string that represents that range of time, rather than a specific time like a timestamp would.

If you have one point per hour and really want to represent those with a BarChart, you can use the Pond static method `Index.getIndexString(period, date)` function to take the date and return an Index string. You'll probably end up with strings that look like 1d-1234. Use those in your inventoryData instead.

```
import { Index } from "pondjs";
const d = new Date("2017-01-30T11:58:38.741Z");
const index = Index.getIndexString("1h", d);   // '1h-412715'
```

Hope this helps?

**Comment by loganbfisher** [comment]
Dude you are a life saver.  Mind if I add this bit of information to the example for bar chart?  I think its good information for others to see as well.

**Comment by pjm17971** [comment]
What would be great is a new example that both explains that, and uses a small set of (say hourly values over a day with hard coded values), to explain how to build a bar chart. The current example page is fine, but it doesn't introduce it well.

**Comment by pjm17971** [comment]
Added a new issue for the docs  (#125), so I'm closing this.
