### ISSUE TITLE
Brush get stuck when is expanded

### ISSUE THREAD

**Issue by caiolopes** [esnet/react-timeseries-charts#141]
If you go to the [cycling example](http://software.es.net/react-timeseries-charts/#/example/cycling) and change the brushed area in order to fill the entire chart, it gets stuck. You can't change it unless you do a zoom in the main chart.

**Comment by caiolopes** [comment]
Another thing: I really think that the brush is really slow compared to a d3 only implementation:

For comparison: https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

What can be the cause of this?

**Comment by pjm17971** [comment]
If you are comparing it to the cycling example, then most likely it's because there's an order of magnitude (at least) more points in the main chart and when you move the brush, it has to redraw that. If you have the same example and it's running slower, can you add a new issue for that and I'll try to profile.

For the original issue, I'll take a look soon. I though initially it was something to do with the handles, but it doesn't seem to be the issue. It will take some debugging.
