### ISSUE TITLE
Grid overlaps chart

### ISSUE THREAD

**Issue by yrokhlin** [esnet/react-timeseries-charts#153]
![image](https://cloud.githubusercontent.com/assets/6445303/26326720/824d18ea-3f0a-11e7-9a5b-0420efa02396.png)

Is there a work around for this?

**Comment by pjm17971** [comment]
Not really.

In our very early charts code (before React) that's the way it rendered, so we kept it. It was because we mostly rendered area charts and wanted to see the lines rendered over it. But I think I would be ok with a change that put it in the background. Likely it would just be a reordering here:
https://github.com/esnet/react-timeseries-charts/blob/master/src/components/ChartContainer.js#L345

If you want to submit a PR for that (checking that it works), I'll probably accept it.

**Comment by susmita-vps** [comment]
Hi @pjm17971 - We're on "react-timeseries-charts": "^0.12.4". Will this be fixed in the near future? Thanks.

**Comment by pjm17971** [comment]
@susmita-vps yes
