### ISSUE TITLE
Custom YAxis Labels

### ISSUE THREAD

**Issue by mustafaibrahim989** [esnet/react-timeseries-charts#160]
Hello,

I asking if it's possible to render a stepped line chart with custom YAxis Labels. For example, YAxis contains only two labels (ON, OFF).

Thanks!

**Comment by pjm17971** [comment]
This isn't possible with a regular axis.

However, if you look at the `LabelAxis` component [1], you should be able to see how to copy this to a `BinaryAxis` component or whatever you want, and customize the SVG rendering however you want. The axis will still need some scale (e.g. min=0 to max=1) so that the chart that refers to it will have a scale, but what the axis renders is up to you (ON, OFF labels).

[1] https://github.com/esnet/react-timeseries-charts/blob/master/src/components/LabelAxis.js
