### ISSUE TITLE
Axis of undefined Error on modifying the currency example chart.

### ISSUE THREAD

**Issue by tech-a-go-go** [esnet/react-timeseries-charts#163]
Hi there,

I'm stuck on modifying the currency example chart.

I've changed data source (fetch from my server) and commented out the Baseline component from the following code line then it caused an error saying Axis of undefined.
https://github.com/esnet/react-timeseries-charts/blob/master/src/website/examples/currency/Index.js#L152

Baseline component is must ? or am I missing something ??

Cheers

**Comment by pjm17971** [comment]
Do you have the code you are rendering with that you can share?

**Comment by tech-a-go-go** [comment]
Hi, 
Thank you for your reply.

I'm sorry, I think it's my fault. I guess how I provide data source to the chart is wrong.

But I still don't know how to pass data source to the chart.
I'm using react-redux.
Do you have any chart examples with react-redux ?

I'm coding like the following and realized now that every time my mouse is over the chart, the render() method gets called and instantiates TimeSeries over and over... this is really stupid.
So first I thought to save an instance of TimeSeries class in Store is good but I was told that saving object in Store is a bad practice.
hm... now I don't know what to do...so stuck.

```
render() {
      const f = format("$,.2f");
      const df = timeFormat("%b %d %Y %X");
      const chartData = this.props.chartData;     <=== this.props.chartData is populated by Redux's connect
      if (!chartData) {
        return;
      }
      const timeSeries = new TimeSeries(
                                                  chartData.name, 
                                                  chartData.columns, 
                                                  chartData.points
                                             );
      const range = timeSeries.range();
      return (
           ...
          <div className="row">
                  <div className="col-md-12">
                      <Resizable>
                          <ChartContainer
                              timeRange={range}
                              maxTime={range.end()}
                              minTime={range.begin()}
            ...
}
```

Cheers

**Comment by pjm17971** [comment]
probably you would want to construct the TimeSeries more like:
```
const timeSeries = new TimeSeries({
    name: chartData.name,
    columns: chartData.columns,
    points: chartData.points
});
```
(though I don't know what exactly is in `chartData`. `name` doesn't matter, should be string though. Columns is a list of strings, and if you are using timestamps for each point, the first column should be "time", and points would be a list of tuples, each tuple in the list is a data point and contains the timestamp (ms since epoch), followed by the value for each of the columns).

your error was something to do with the axis, but that's removed from the render you pasted in. Make sure you have an axis and that its id is "y" (as referenced by the LineChart. 

Other than that, I don't have an example of using redux, but it should just be injecting new data into your component via chartData, so that should be fine.

**Comment by tech-a-go-go** [comment]
Hi, 
Thank you !
I will look into it !
