### ISSUE TITLE
Auto adjust of the bar size of BarCharts in a resizable chart container

### ISSUE THREAD

**Issue by tech-a-go-go** [esnet/react-timeseries-charts#198]
Hi there,

I have two BarChart components in a single chart row to show bars side by side.

I set spacing=1 to them but they get overwrapped each other.
So I set size=1 but bars are way too thin if I expand my browser. (Plz forget about the offset property)

I want bars to be adjusted automatically by depending on the chart container size.
Is it possible ??

Cheers.

**Comment by pjm17971** [comment]
If you want them to resize out with the window, then you are saying you want them to occupy a time range, rather than be positioned centered (or offset) at the center of the time range. So your answer is probably to remap the events in the timeseries to TimeRangeEvents, and tell it exactly what timerange each bar should take up. However, from a UI perspective, I don't know if that's a good idea because if you have two values for an hour and want to display them side by side, remapping them into each half hour would have the effect you describe, but you'd be strongly implying that the values where for those half hours. This is why this isn't a standard behavior of the bar charts.

I think you want a combination of size and offset, where size will hard code the number of pixels wide each bar will be and offset will move each bar out from the center of its time range. Here's the example of this:

https://github.com/esnet/react-timeseries-charts/blob/master/src/website/packages/charts/examples/volume/Index.js#L322

**Comment by tech-a-go-go** [comment]
Thank you for your reply !

That helped me a lot. :)

Cheers
