### ISSUE TITLE
Documentation shows improper use of `series.min()` and `series.max()`

### ISSUE THREAD

**Issue by Eric-Arellano** [esnet/react-timeseries-charts#204]
Several [instances of the documentation](http://software.es.net/react-timeseries-charts/#/example/baselines?_k=dtpt4j) show calling `timeseries.max()` and `timeseries.min()`, but this wasn't working for me in my project, which—if I understand the Pond code correctly—I think is because `min` and `max` require a parameter.

This is the [pond type description](http://software.es.net/pond/#/class/timeseries) for the timeseries function:
```typescript
max(fieldPath?: string, filter: any): number
```

I got my code to work once I changed `series.min()` to `series.min('value')`, referring to the column name in my time series constructor. 

--

I'd be happy to help fix the docs if you point me in the right direction with how to do so!

**Comment by pjm17971** [comment]
The charts react-timeseries-charts refer to Pond 0.8.x (and before), where a column of "value" is supposed to be the default.

The new version of Pond (1.0 alpha) does away with that. Originally the idea was that for an Event, you could just specify the timestamp and a value say 2 (rather than a timestamp and a map of values), but the result was actually {value: 2}. It was convenient as a short cut, but ultimately a source of confusion.

Once there's a react-timeseries-charts version fully compatible with the new version of Pond, that should be clearer assuming all the docs changes are caught. There's a PR for the Pond 1.0 alpha version of the charts code, but it needs some work. You are welcome to try it though, I'll be spending some time on it later this week. Docs updating would be really helpful, if you have any time to devote to that. Docs are built off the comments in the code and several markdown files (for the guides).
