### ISSUE TITLE
TimeRange-normalizing by weeks

### ISSUE THREAD

**Issue by boriskogan81** [esnet/react-timeseries-charts#207]
I'm trying to build charts showing crop development over a year, between several seasons. 

I know that the TimeRange is set like this:

`<ChartContainer timeRange={series1.timerange()} />
`
I have different timeseries, of course, from the different seasons.

I'd like to stack the charts one on top of the other, and normalize them to weeks, so that the x-axis goes from 0-52 weeks, but you can still see the date of a particular event or measurement when hovering over it. 

I'd renormalize the initial data to weeks, but am afraid that would not meet the second requirement.

How should I build the TimeRange?

**Comment by pjm17971** [comment]
There's no real way to normalize to weeks like that. The time axis always represents an actual begin and end time in history (Jan 1 2017 to Dec 31 2017) defined in the `ChartContainer`. Basically, there's one of these per `ChartContainer`, not multiple as in your case. I guess your time axis might be considered a set of categories, one for each week, not a time axis at all, so this might not be the library for you.

Having said that, it might work to remap all your data to 1970 and then set the format (`ChartContainer`'s `format` prop) to "month" -- there's no "week" in the library. I'm not sure if you'd end up with "1970" rendered along the axis though.

Having it display the right thing in the tracker isn't hard because you can take the time it gives you (some time in 1970) and remap that to the original datasets. You provide the `trackerValues`.

Sorry I don't have a better answer for you. This kind of thing comes up from time to time, so it might be something to provide more direct support for down the road.
