### ISSUE TITLE
Performance enhancements for large datasets

### ISSUE THREAD

**Issue by davegravy** [esnet/react-timeseries-charts#219]
Issue [#92](https://github.com/esnet/react-timeseries-charts/issues/92) and [#174](https://github.com/esnet/react-timeseries-charts/issues/174) talk about this. There is a recommendation to "use pond to crop the data to the visible time range on each render" and use rollups to downsample the data to a resolution appropriate for the zoom-level. 

Are there any examples showing this? I assume that I would keep my uncropped read-only `this.state.masterTimeSeries` and in the `onTimeRangeChanged` handler i would `setState({viewTimeSeries: this.state.masterTimeSeries.crop(timerange})`?

Is there a performance benefit to downsampling before cropping, vs the opposite order?

Is all of this still necessary to do (in one of the other issues it mentioned this functionality may be in-built soon)?

**Comment by pjm17971** [comment]
Usually the best place for rollups is the server combined with some backend process, as there's ultimately a limit on how much you can do client side (how much data do you really want to ship to a browser, how much time are you willing to wait to aggregate that data down to realistically render it).

You can look at the cycling example for how to do this. It takes a rather large dataset and builds multiple rollup levels for multiple channels. Unfortunately this comes at the cost of having the user wait while it builds those. You can also just build them as you need them (build the rollup for the most zoomed out view), then build the others later. That way the user isn't waiting so long to get some view.

To answer your other questions:
 - yes, keep around the master timeseries
 - also keep around any rollup work you do, because that's somewhat expensive depending on how big your dataset is
 - you can just crop the rollup level or master level as you render it, cropping is pretty quick usually so you probably won't need to keep it in state.

And yes, it's mostly still necessary to do this, with the exception of the box plot (which is by its nature trying to show data summary). The problem is this is very case specific, and in the end there's only a range of data sizes for which this is useful. So while I think that would still be useful, backing up this kind of thing with Pond is still an approach I'm happy with.

Hope this helps (or at least clarifies).
