### ISSUE TITLE
Last label on TimeAxis is cut off

### ISSUE THREAD

**Issue by barbaragomes** [esnet/react-timeseries-charts#227]
How can I fix this:

![screen shot 2018-03-02 at 5 11 07 pm](https://user-images.githubusercontent.com/13023284/36928696-e59d92a0-1e3c-11e8-854a-4246e363aa10.png)

Last label should be 00:10, but the last 0 is cut off

**Comment by rainitesh** [comment]
I have been facing the same issue. Also is there a way to move the label at 45 degrees angle. Since I have a long value it  gets very cluttered.

**Comment by pjm17971** [comment]
I'm going to add a `padding` (and `paddingLeft`, `paddingRight`) prop to the `ChartContainer` to address the first issue here (clipped label). It will add a black area to the left and/or right of the charts/axes so that the label is cut off by the svg bounds. As long as you supply enough padding to the right (in the above example) for the worst case label to fit, it will render ok. It will be removed when the tick mark itself is out of the timerange.

**Comment by pjm17971** [comment]
For the other issue, angled labels, would something like this work?

<img width="525" alt="screen shot 2018-03-06 at 9 15 30 am" src="https://user-images.githubusercontent.com/1288813/37047357-7e0ece8e-211f-11e8-8843-09188f252b10.png">

I'll also add a prop to control the height of the x-axis, which you'll probably need to change for long labels.

**Comment by rainitesh** [comment]
@pjm17971 I'll test the padding and let you know. The angled labels look good to me. Are they already available or do you need to push those changes?
