### ISSUE TITLE
Caching TimeSeries

### ISSUE THREAD

**Issue by tech-a-go-go** [esnet/react-timeseries-charts#228]
Hi there,

I have the following method and it gets called 10 times per sec.
```
createScoreTimeSeries() {
    const events = _.map(scoreEventBuffer.toArray(), (scoreEvent) => {
      return scoreEvent.event;
    });
    const scoreTimeSeries = new TimeSeries({
      name: 'score',
      collection: new Collection(events),
    });
    return scoreTimeSeries;
  }
```
It's kinda heavy and I think instantiating both TimeSeries instance and Collection instance everytime the method gets called is wasting resources so I've decided to cache both instances like below.
```
createScoreTimeSeries() {
    // retrieve only added events since last time
    const events = _.map(scoreEventBuffer.toDeltaArray(new Date().getTime()), (scoreEvent) => {
      return scoreEvent.event;
    });

    if (this.collection) { // use the cached collection if exists
      _.forEach(events, (event) => {
        this.collection.addEvent(event);
      }
    } else { // create a cache
      this.collection = new Collection(events);
    }
    
    if (this.scoreTimeSeries) { // use the cached time series if exists
      this.scoreTimeSeries.setCollection(this.collection);
    } else { // create a cache
      this.scoreTimeSeries = new TimeSeries({
        name: 'score',
        collection:  this.collection,
      });
    }
    return this.scoreTimeSeries;
  }
```
 But the chart didn't show anything with cached ones.

Am I doing wrong ??
I'd like to know how to cache collection and time series properly.

Cheers

**Comment by pjm17971** [comment]
Well one thing to know is that a `TimeSeries` contains a `Collection`.

If you ask a series for its collection you get a reference to the one inside the series. If you mutate that by adding an event you will get a new collection as efficiently as possible. When you add the collection into a new TimeSeries this will be very light, because it will just refer to the collection, not copy or recreate.

We cache the TimeSeries. If Events are added to it, we create a modified TimeSeries and then cache that. The difference between a Collection and a TimeSeries containing that Collection isn't worth worrying about.
