### ISSUE TITLE
Error when changing min and max on YAxis

### ISSUE THREAD

**Issue by Haykys** [esnet/react-timeseries-charts#231]
Hey guys,

So I have my chart designed like this

```
<ChartContainer
            timeRange={this.props.weather.series.timerange()}
            width={800}
          >
            <ChartRow height="200">
              <YAxis
                id="axis1"
                label="Temperature"
                min={this.props.weather.series.min()}
                max={this.props.weather.series.max()}
                width="60"
                type="linear"
              />
              <Charts>
                <LineChart axis="axis1" series={this.props.weather.series} />
              </Charts>
            </ChartRow>
          </ChartContainer>
          <button
            onClick={this.handleShowHumidity.bind(this)}
            type="submit"
            className="btn btn-secondary"
          >
            Show Humidity
          </button>
```
Purpose of my app is to show weather information about different cities.
Initially the YAxis renders correctly with correct min and max. But when I try to search for other city, i get error 
`TypeError: (0 , _d3Selection.select)(...).select(...).transition is not a function` and nothing happens
I know the problem is in min max of YAxis because when I hardcode values then it works.
Any idea what I'm doing wrong ?

**Comment by pjm17971** [comment]
I'm not sure, that piece of code looks fine. I wonder if you are passing in a bad value as the city transitions. Maybe you could look at `this.props.weather.series.min()` etc to see if you always are getting a reasonable value rendered there.

**Comment by sartaj10** [comment]
I'm closing this for now since there is no further information available.

**Comment by llaver** [comment]
I had the same problem and did some research. This is happening due to the YAxis component always returning false for `componentShouldUpdate`... I would assume there is some reason for this decision, but I cannot for the life of me understand why.

So the only solution is to update `componentShouldUpdate` in the library or unmount then remount the whole component in your project.

**Comment by pjm17971** [comment]
@llaver because d3 is controlling the DOM below this component, the component doesn't re-render in the same way because that would take control from d3. Instead it uses the props change to force d3 to re-create / alter the DOM that it controls. I'm not saying there isn't a bug there, but that's why shouldComponentUpdate returns false.

**Comment by llaver** [comment]
Good to know the why, so do you know where it handles taking new props and rerendering? Obviously it's forgetting to check a few props 😜
