### ISSUE TITLE
Error when rendering lineChart using column name other than "value"

### ISSUE THREAD

**Issue by rweller59** [esnet/react-timeseries-charts#234]
When using columns in lineChart definition, I get the following error:
LineChart.js:264 Uncaught TypeError: Cannot read property 'normal' of undefined
    at LineChart.pathStyle (LineChart.js:264)
    at LineChart.renderPath (LineChart.js:301)
    at LineChart.renderLine (LineChart.js:384)
    at LineChart.js:325

Series defined as:
   const airTemp= new TimeSeries({ 
      name: "airTemp", 
      columns: ["time", "airtemp"], 
      points: this.dataPoints() });

Error when rendering like this: 
    <LineChart axis="Temperature" series={airTemp} columns={["airtemp"]} style={style} />

No Error and no line drawn when rendering like this:
    <LineChart axis="Temperature" series={airTemp} style={style} />

Changing series definition like this... columns: ["time", "value"],
(i.e., changing column name to "value" from "airtemp")
No Error and line drawn as expected when rendering like this:
    <LineChart axis="Temperature" series={airTemp} style={style} />

**Comment by rweller59** [comment]
figured it out (amazing what a night's sleep will do). Didn't catch the connection between the style key and the column name, i.e., style did not have key that equaled column name

**Comment by brandly** [comment]
@rweller59 can you explain this more? i'm unclear on what you mean by "the connection between the style key and the column name."

currently, if i do `columns: ['time', 'temp']`, i get `Cannot read property 'normal' of undefined`. if i do `columns: ['time', 'value']`, i get no errors in the console but no line is rendered either. i'm not sure what's going wrong.

**Comment by brandly** [comment]
hm. so when you use `value`, no error gets thrown and i'm not sure why. 

here's what i was doing wrong tho, in case others come across this:

```js
const style = styler([
  { key: 'wind', color: scheme.wind }
])

...

<LineChart
  axis={label}
  series={series}
  columns={['not wind']}
  style={style}
/>
```

since that name in `columns` is not a `key` in `style`, the error would get thrown i think

**Comment by pjm17971** [comment]
The `columns` in the `TimeSeries`, the `key` in the `styler` and the `columns` in `LineChart` all refer to the same data, so need to match. `value` is typically a default though, so that's probably why no error is seen for that case. Basically you would define a `TimeSeries` with a specific data column like `wind`, but maybe with other columns. To render it and potentially other columns you'd use `wind` in the `LineChart` columns prop (but `value` is a default). The styler maps onto that column of data with its `key` field, followed by some high level styling to say "wind is blue". It would probably be better if the styler used column instead of key, but it's kind of hard to change now.

**Comment by brandly** [comment]
Thanks Peter! Makes sense. API changes are always hard. 

Most of what I’ve done with this library has been thru looking at the examples followed by some trial and error. It has saved me a lot of time getting some prototypes up and running tho. Thanks for the help!
