### ISSUE TITLE
TimeAxis and YAxis do not rerender after style prop changes

### ISSUE THREAD

**Issue by mikol** [esnet/react-timeseries-charts#370]
# 🐛Bug report

**Describe the bug**
Both `TimeAxis` and `YAxis` aggressively filter updates. They don’t rerender via React ever (`shouldComponentUpdate()` always returns `false` and `render()` is only used to insert an SVG `g` element). They include a set of gates in `componentWillReceiveProps()` to determine granularly which elements should be updated. These gates don’t account for all possible prop changes, which is why we don’t see the components rerendering in this and other cases. 

See also: https://github.com/esnet/react-timeseries-charts/issues/346

**To Reproduce**
1. Set `ChartContainer` `timeAxisStyle` prop (e.g., `{values: {fill: '#c00'}}`)
2. Change `ChartContainer` `timeAxisStyle` prop on any subsequent render (e.g., `{values: {fill: '#fc0'}}`)
3. Note that the time axis styles like tick label fill do not update

Follow a similar procedure with `YAxis` `style` prop and note that the axis styles like label fill do not update.

**Expected behavior**
`TimeAxis` and `YAxis` should rerender whenever they receive changed props.

**Desktop (please complete the following information):**
 - OS: macOS Sierra 10.12.6 (16G1815)
 - Browser: Chrome
 - Version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by khoama** [comment]
It looks like the YAxis is set to always ignore new prop changes. Not sure if this is a mistake or not https://github.com/esnet/react-timeseries-charts/blob/master/src/components/YAxis.js#L178

**Comment by mikol** [comment]
@khoama – It seems intentional to me. The initial render adds an SVG `g` element, and then updates are managed manually via `componentWillReceiveProps()`.

**Comment by pjm17971** [comment]
The axis code still uses d3 to render the chart. When all prop changes caused a re-render of the axis code this featured very high in profiling we did (this was years ago now though). So, we started being selective about the updates as well as some updates doing a more minimal DOM manipulation where possible.

That's the background here.

Ultimately we wrote react-axis so that we could replace this d3 code and not have to deal with this, but we're lacking the resources to finish that work right now. I am hopeful we can make some progress on this project in the coming 6 months though as there's some internal drivers for that.
