### ISSUE TITLE
How to style ChartRow time axis?

### ISSUE THREAD

**Issue by ontofractal** [esnet/react-timeseries-charts#84]
What props do I have to pass to the ChartRow component to style its time axis and ticks? For example, if I want to increase contrast and strokeWidth of time axis.

YAxis styling is quite straightforward as described in the docs, so is there something similar for TimeAxis?

There are styling options for [TimeAxis](http://software.es.net/react-timeseries-charts/#/api/TimeAxis?_k=0yrnm1) but it seems that TimeAxis doesn't draw over ChartRow. I wasn't able to find any time axis styling in the examples.

**Comment by pjm17971** [comment]
In theory you control the time range and style of the TimeAxis via the ChartContainer, since everything under the ChartContainer shares the same x axis. However, this apparently didn't work for styling because the style wasn't being forwarded onto the TimeAxis.

Sorry for the confusion.

I've just pushed a fix for this, so give it a try: v0.10.2. The DDoS example has a modified style for both the x and y axis:
https://github.com/esnet/react-timeseries-charts/blob/master/src/website/examples/ddos/Index.js#L123

**Comment by ontofractal** [comment]
Got it, thanks for the information and fast fix!
