### ISSUE TITLE
PropTypes validation, instanceOf, TimeRange, TimeSeries

### ISSUE THREAD

**Issue by primozs** [esnet/react-timeseries-charts#90]
If I pass instance of TimeSeries or TimeRange from redux store then I get the warnings:

Warning: Failed prop type: Invalid prop `timeRange` of type `TimeRange` supplied to `ChartContainer`, expected instance of `TimeRange`

Warning: Failed prop type: Invalid prop `series` of type `TimeSeries` supplied to `LineChart`, expected instance of `TimeSeries`

When I only get points from redux store and instantiate TimeSeries in component constructor, then warnings don't appear. 
Any suggestion how to avoid this?
Cheers

```
ChartContainer
timeRange: React.PropTypes.instanceOf(TimeRange).isRequired

LineChart
series: React.PropTypes.instanceOf(TimeSeries).isRequired,
```

**Comment by pjm17971** [comment]
I think this warning would come about if the type checking of the ChartContainer was using a different version of TimeRange than the code that is passing it in as a prop. We used to see this when Pond was a dependency (rather than peer dependency) of the charts library and then people used their own version of pond that wasn't the same. Perhaps you have two versions of Pond installed somehow?

**Comment by primozs** [comment]
@pjm17971 Hi, yes you were right. I am using now peer dependency spec. and the warnings are gone.
Thank you for your help!
Cheers
