### ISSUE TITLE
How to optimize tracker position display with larger data

### ISSUE THREAD

**Issue by primozs** [esnet/react-timeseries-charts#92]
Maybe somebody can find this useful:

When you set "trackerPosition" property on ChartContainer and update the state the whole Chart is redrawn. One way to only update TimeMarker is to make custom TimeMarker component and connect it with redux. This way, when tracker changes only custom TimeMarker is redrawn instead of the whole chart.

Custom TimeMarker

```
import React, { PropTypes } from 'react';
import { connect } from 'react-redux';
import { TimeMarker } from 'react-timeseries-charts';
import { getTracker } from '...redux actions';

class BaroMarker extends React.Component {
  render() {
    const { tracker, infoValues, infoStyle } = this.props;

    return (
      <TimeMarker
        {...this.props}
        time={tracker}
        infoStyle={infoStyle}
        infoValues={infoValues}
      />
    );
  }
}

BaroMarker.propTypes = {
  infoValues: PropTypes.string,
  infoStyle: PropTypes.object
};

BaroMarker.defaultProps = {
  infoValues: '',
  infoStyle: {
    line: {
      strokeWidth: "2px",
      stroke: "red"
    }
  }
};

const mapStateToProps = (state) => {
  return {
    tracker: getTracker(state.charts)
  };
};

export default connect(
  mapStateToProps
)(BaroMarker);
```

Use

```
handleTrackerChanged(tracker) {
    if (tracker) {
      setTracker(tracker); // redux action
    }
}

<Charts>
     ....
    <BaroMarker axis="altitude" />
</Charts>
```

Any other idea how to redraw chart faster with larger data?
Or, how to make zoom pan faster?
Display only simplified data with the similar shape on lower zooms but full data on higher zooms?
Cheers

**Comment by pjm17971** [comment]
That's cool. That's exactly why the `<TimeMarker>` is factored out now. I can try an incorporate this into the docs. It's actually pretty easy to add your own charts, I'm surprised when people balk at it.

So I guess though I'm wondering why this is needed here. What are you rendering in `<Charts>` that is redrawing, and any idea what is getting through the `shouldComponentUpdate()` in that? Some amount of work has been put in to prevent redraws of charts when the tracker is moved, but sounds like something is triggering a re-render in your case, or that code has since broken in some way.

To make the chart render faster, that generally comes down the the density of the data you're drawing. First, use pond to crop the data to the visible time range on each render. That is generally faster than letting the charts code deal with all that SVG drawing. In addition, you can use pond to down sample your data in advance () and then use the time range to control which resolution you send to the chart.

```
 const timeseries = new TimeSeries(data);
 const dailyAvg = timeseries.fixedWindowRollup({
    windowSize: "5m",   // 5 min avg
    aggregation: {value: {value: avg()}} // dest_column: {src_column: aggregation_func()}
 });
```
The next version of the charts library will hopefully address some of this automatically, but its obviously a tradeoff between the price of down sampling and the price of generating all that SVG, so at some level its better to manage data density outside the library. Internally, we pre-bake timeseries tiles at different resolutions, then merge them together and the user pans and zooms.

**Comment by primozs** [comment]
Hi,
I did it like this because if you are using setState to change trackerPosition in container component that is rendering ChartComponent then the whole Chart is re-rendered just because state for the tracker position has changed. 

fixedWindowRollup: This works great but i have one additional question:
My data has multiple columns and and position column is array of lon lat: 
```
     const dataFull = new TimeSeries({
          name: 'Track',
          columns: ['time', 'altitude', 'position'],
          points: trkPoints
        });
```
How could I add position column to aggregation? I could not find it Pond documentation.
```
       const data =
          trkDataFull.fixedWindowRollup({
            windowSize: '1m',
            aggregation: {
              altitude: { altitude: avg(filter.ignoreMissing) },
              position: { position: } ??
            },
            toEvents: true
          });

```
Thank you for your help and great library!

**Comment by primozs** [comment]
I found it!
```
const data =
          trkDataFull.fixedWindowRollup({
            windowSize: '1m',
            aggregation: {
              altitude: { altitude: avg(filter.ignoreMissing) },
              position: { position: keep(filter.ignoreMissing) }
            },
            toEvents: true
          });
```
Thank you!

**Comment by pjm17971** [comment]
Yep that will work. That's pretty useful if you are grouping by a key, aggregating, and then want to keep that key for a following step. You can also use `first()` or `last()`. And then you could pull the deep values out using the dot notation.

```
const data = ts.fixedWindowRollup({
    windowSize: '90d',
    aggregation: {
      value: { value: avg() },
      pos_x_avg: { "position.0": avg()},
      pos_y_avg: { "position.1": avg()}
    },
    toEvents: true
});
```
