### ISSUE TITLE
Unable to disable PanZoom

### ISSUE THREAD

**Issue by patryk0605** [esnet/react-timeseries-charts#96]
Using the following snippet: 

```jsx

<Resizable>
  <ChartContainer
    timeRange={timerange}
    enablePanZoom={false}
    maxTime={trafficSeries.range().end()}
    minTime={trafficSeries.range().begin()}
    minDuration={1000 * 60 * 60}
    onBackgroundClick={() => this.setState({selection: null})}
    onTimeRangeChanged={::this.handleTimeRangeChange}
  >
    <ChartRow height="350" debug={false}>
      <Brush
        timeRange={this.state.brushrange}
        allowSelectionClear={true}
        onTimeRangeChanged={::this.handleBrushTimeRangeChange}
      />
      <Charts>
        <AreaChart
          axis="traffic"
          series={trafficSeries}
          columns={{up: ['in'], down: ['out']}}
          style={upDownStyle}
          highlight={highlight}
          onHighlightChange={highlight => this.setState({highlight})}
          selection={selection}
          onSelectionChange={selection => this.setState({selection})}
        />
      </Charts>
      <YAxis id="traffic" label="% Utilization" labelOffset={0} min={-max} max={max} absolute={true} width="60" type="linear" format=".0%" />
    </ChartRow>
  </ChartContainer>
</Resizable>

```

PanZoom is still functional even though I have `enablePanZoom={false}`. Am I missing something? Also, is there a way to keep the zoom, but remove the pan?

**Comment by pjm17971** [comment]
Generally, you control the timerange that is displayed with the `timeRange` prop, while you are given a callback for the proposed new timerange in the `onTimeRangeChanged` callback. To implement pan and zoom, you can take that timerange and feed it back into the chart container. On the other extreme you can not use that callback and the chart will never pan or zoom.

For zooming and not panning, can you describe specifically what you're trying to achieve? Do you want it to not pan even when zoomed in, or just when you are showing the whole dataset. That latter is possible using the max and min time. But the other isn't, because you can't, at this point, independently constrain the pan action from the zoom action. They are both building a new timerange that is then constrained. That would be possible, but I'd like to hear why you'd do that. It's kind of fundamental. This is the use case that works:
http://software.es.net/react-timeseries-charts/#/example/traffic

Using `enablePanZoom` was intended to cut the event handling internally and aesthetically not display the hand cursor on those events, but that does seem to be broken. I'll put in a fix for that and hopefully push out a patch. In the mean time, I think the above method basically gets you a disabled pan/zoom.

**Comment by patryk0605** [comment]
To give you an idea of what I am doing (ignore values, still in development): 

![image](https://cloud.githubusercontent.com/assets/7227636/19901557/cfaec6b8-a03d-11e6-9d86-d6845aa456ec.png)

I am using the `Brush` to allow the user to select a time range to view the top 10 most active processes at that time. If the user zooms in on the chart and tries to move the `Brush`, it becomes unusable because it's trying to pan the time series data and `Brush` at the same time. This is why I would like to disable the pan, so a user can still zoom in on a time series set and use the `Brush` to select what time frame in the current view they want to view the processes for.

**Comment by pjm17971** [comment]
If I understand what you are doing correctly:

You have (1) the timerange for all your data (say, `timerange`), (2) the timerange for the displayed data (let's say we call that `zoomTimerange`, which is the extents of the graph shown above), and (3) the timerange for your brush, which you need to drive the top processes (say we call that `selectionTimerange`), which is basically a selection. 

So in general the brush isn't really supposed to be for selection like that, though I can certainly see why it is being used like that (you're not the only one). So let's see what we can do here.

I think I'd probably suggest showing the user a main chart and an overview chart to separate these things out from an interactivity point of view.

For the overview chart, you just leave pan and zoom on the background chart (mouse drag etc) and use that to drive `zoomTimerange`. Constrain that to `timerange` with the `maxTime` and `minTime`.

For the main chart, use `zoomTimerange` at the timerange in the ChartContainer's `timeRange` prop. That gives the user the ability to navigate around the full data, using the brush in the overview. You'd not want to respond to any pan/zoom on this window. Then you can add the selection brush on top of this window which would control the `selectionTimeRange` only, not the pan and zoom of the chart at all.

I think this would work now.

Going forward, I wonder if we should allow the user to shift-drag or something to define a new selection brush to separate out the events here. I'll keep thinking about that. Anyway, thanks for the example. That's always useful. We actually want to support something like that (in our case, select a timerange to tag or bookmark that timerange), so a good single chart solution is worth thinking about.

**Comment by patryk0605** [comment]
A shift drag would definitely be nice! As per your suggestion, are you saying to building something along the lines like here: http://software.es.net/react-timeseries-charts/#/example/cycling?_k=a4qh6s

Also, would like to say thanks again for the great amount of detail you provide in your posts. Has been very helpful!

**Comment by patryk0605** [comment]
Actually, would PR #91 solve my issue?

**Comment by pjm17971** [comment]
Perhaps partially it would help, but it's more about allowing the user to do something when the drag events end rather than as they happen. It lets you do a different type of zoom, where you select and area and then as you release you zoom. We don't really do things that way, but it seems reasonable to give that event hook.

Yes, that example is basically what I mean, though you'd style a separate brush on the main chart to represent selection.

Regarding the shift-drag, I was also thinking you could have it be mode based, where the UI might have a select icon and a pan icon that put the app into pan mode, or a selection mode. This would be analogous to drawing programs where you could draw a line, or select and move a line. Another option. Unfortunately today there isn't a great way of doing this other than to separate things out like described above.

**Comment by patryk0605** [comment]
Any update on when `enablePanZoom={false}` will be fixed?

**Comment by pjm17971** [comment]
We discussed a bunch of things above, but I just pushed a change into the v0.12 branch of mine which avoids handling of pan/zoom events when enablePanZoom={false}. I'm thinking of stoping at that and seeing if that helps you.

I'm still not sure of the right solution to be able to select an area and pan/zoom on a single chart, however. But still something I'd like to solve.

**Comment by patryk0605** [comment]
I've tried out your change on the v0.12 branch and it's working just as expected. Thanks! Do you have a planned date on when to merge with master?

**Comment by pjm17971** [comment]
Yeah, I'm thinking of merging and releasing some more minor changes/fixes tomorrow ("open source day"), and aligning it with the new version of Pond, which has a couple of breaking changes I want to get past. But such plans often derail, so I'll just say sooner rather than later.

**Comment by patryk0605** [comment]
Sounds good, thanks again!
